## SPDX-FileCopyrightText: The go-mail Authors
##
## SPDX-License-Identifier: MIT

version = '2'

[run]
go = '1.25'
tests = true

[linters]
enable = [
  'containedctx',
  'contextcheck',
  'decorder',
  'errname',
  'errorlint',
  'gosec',
  'staticcheck',
  'whitespace'
]

[linters.exclusions]
generated = 'lax'
presets = [
  'comments',
  'common-false-positives',
  'legacy',
  'std-error-handling'
]
paths = [
  'examples',
  'third_party$',
  'builtin$',
  'examples$'
]

[formatters]
enable = [
  'gofmt',
  'gofumpt'
]

[formatters.exclusions]
generated = 'lax'
paths = [
  'examples',
  'third_party$',
  'builtin$',
  'examples$'
]

## Cannot overflow, since check this value at config initialization
[[linters.exclusions.rules]]
linters = [
  'gosec'
]
path = 'internal/presenter/presenter.go'
text = 'G115:'

[[linters.exclusions.rules]]
linters = [
  'gosec'
]
path = 'internal/service/service_test.go'
text = 'G115:'
