# SPDX-FileCopyrightText: Winni Neessen <wn@neessen.dev>
#
# SPDX-License-Identifier: MIT

## -----------------------------------------------------------------------------
## General Configuration
## -----------------------------------------------------------------------------

## Measurement units for weather data.
## Accepted values: "metric" or "imperial"
## Default: "metric"
units = "imperial"

## Locale setting for geolocation services.
## If left empty, the application will attempt to detect it automatically
## using the LC_MESSAGES environment variable.
# locale = "en-US"

## Log level for informational and error messages.
## Available levels:
##   DEBUG = -4
##   INFO  = 0
##   WARN  = 4
##   ERROR = 8
## Default: 0 (INFO)
loglevel = 0

## -----------------------------------------------------------------------------
## Weather
## -----------------------------------------------------------------------------
[weather]

## Forecast duration.
## Specifies how many hours ahead to display forecast data.
## Default: 3
forecast_hours = 5


## -----------------------------------------------------------------------------
## Intervals
## -----------------------------------------------------------------------------
[intervals]

## Weather update interval.
## Defines how frequently the application queries the Open-Meteo API
## for updated weather data.
## If a geolocation change is detected by Geoclue, an update is triggered automatically.
## Default: 15m
weather_update = "30m"

## Output interval.
## Specifies how often waybar-weather outputs JSON data to Waybar.
## A geolocation change detected by Geoclue will also trigger an update automatically.
## Default: 30s
output = "15s"


## -----------------------------------------------------------------------------
## Templates
## -----------------------------------------------------------------------------
[templates]

## Text template.
## Defines the primary text displayed in the Waybar weather widget.
## Uses Goâ€™s templating syntax for customization.
## Refer to README.md for details.
## Default: {{.ConditionIcon}} {{.Temperature}}{{.TempUnit}}
text = ""

## Tooltip template.
## Defines the tooltip content displayed for the weather widget in Waybar.
## Supports Go templates and custom formatting.
## Default:
##   Condition: {{.Condition}}
##   Location: {{.Address.City}}, {{.Address.Country}}
##   Sunrise: {{timeFormat .SunriseTime "15:04"}}
##   Sunset: {{timeFormat .SunsetTime "15:04"}}
##   Moonphase: {{.MoonphaseIcon}} {{.Moonphase}}
##   Forecast for: {{timeFormat .WeatherDateForTime "15:04"}}
tooltip = ""


## -----------------------------------------------------------------------------
## Geolocation
## -----------------------------------------------------------------------------
[geolocation]

## Geolocation provider configuration.
## Disable specific providers used to determine location data.
## All providers are enabled by default.
disable_geoip = true
disable_geoapi = true
disable_geolocation_file = true
disable_ichnaea = true