# SPDX-FileCopyrightText: Winni Neessen <wn@neessen.dev>
#
# SPDX-License-Identifier: MIT

## Units used for weather data (allowed values "metric" or "imperial")
#
# Default: "metric"
units = "imperial"

## Locale used for geo location services (if empty, tries to automatically get
## it from the LC_MESSAGES environment variable)
#
#locale = "en-US"

## Log level used for informational/error messages
# DEBUG = -4
# INFO = 0
# WARN = 4
# ERROR = 8
#
# Default: "0" (for INFO)
loglevel = 0

## Weather data mode
# Can be either "current" or "forecast"
# In forecast mode it will show future weather data of up to 24h ahead (see forecast_hours)
#
# Default: "current"
weather_mode = "forecast"

## Forecast hours
# The amount of hours that the forecast should reflect
#
# Default: 3 hours
forecast_hours = 5

[intervals]
## Weather update intervale
# The interval in which the Open-Meteo API is checked for weather updates
# If a geo location change is detected by Geoclue, a weather is triggered automatically
#
# Default: 15m
weather_update = "30m"

## Output interval
# The interval in which waybar-weather outputs the JSON with the current information to
# Waybar. If a geo location change is detected by Geoclue, a weather is triggered
# automatically.
#
# Default: 30s
output = "15s"

## Templates allow the user to make their waybar-weather widget look the way the prefer
## It uses the Go templating system and it highly customizable. Check the README.md for details
[templates]
## Text template that is displayed as main text in the waybar
#
# Default: {{.ConditionIcon}} {{.Temperature}}{{.TempUnit}}
text = ""

## Tooltip template that is displayed as waybar tooltip for the weather widget
#
# Default: Condition: {{.Condition}}\nLocation: {{.Address.City}}, {{.Address.Country}}\nSunrise: {{timeFormat .SunriseTime \"15:04\"}}\nSunset: {{timeFormat .SunsetTime \"15:04\"}}\nMoonphase: {{.MoonphaseIcon}} {{.Moonphase}}\nForcast for: {{timeFormat .WeatherDateForTime \"15:04\"}}
tooltip = ""